version: '3'
services: 
  nginx:
    depends_on:
        - react-front-reddit
        - express-server-reddit
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - '80:80'
      - '443:443'
  react-front-reddit:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile
    #ports: 
    #  - '3002:3002'
    restart: on-failure
  express-server-reddit:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./docker-env/node/app.env
    #ports: 
    #  - '4001:4001'
    command: sh -c "sleep 3 && npm run unmigrate && npm run migrate && npm run seed && npm start"
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    env_file: 
      - ./docker-env/postgres/app.env
    ports:
      - "5432:5432"